/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import revenda.Car;
import revenda.CarDAO;

import java.awt.Component;
import java.lang.reflect.Field;

import javax.swing.*;

/**
 *
 * @author Lucas
 */
public class jifcadastro extends javax.swing.JInternalFrame {

    private String[] selectAnos;
    private Car editCar;

    /**
     * Creates new form jifcadastro
     */
    public jifcadastro(Car c) {
        this.init();
        this.editCar = c;
        this.preencheEditFormCar();
    }

    public jifcadastro() {
        this.init();
    }

    private void init() {
        selectAnos = new String[150];

        for (int i = 0; i < 150; i++) {
            selectAnos[i] = (i + 1950) + "";
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        Cancelar = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelNome = new javax.swing.JLabel();
        inputNome = new JTextField();
        jLabel1 = new javax.swing.JLabel();
        inputAnoModelo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputAnoFabricacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputCombustivel = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputPlaca = new JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputMarca = new JTextField();
        jLabel8 = new javax.swing.JLabel();
        inputModelo = new JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        checkArCondicionado = new javax.swing.JCheckBox();
        checkAirBag = new javax.swing.JCheckBox();
        checkCdPlayer = new javax.swing.JCheckBox();
        checkDirecaoHidraulica = new javax.swing.JCheckBox();
        checkVidroEletrico = new javax.swing.JCheckBox();
        checkTravaEletrica = new javax.swing.JCheckBox();
        checkCambioAutomatico = new javax.swing.JCheckBox();
        checkAlarme = new javax.swing.JCheckBox();
        checkZeroKm = new javax.swing.JCheckBox();
        checkDesembacadorTraseiro = new javax.swing.JCheckBox();
        checkRodasLiga = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        inputKilometragem = new JTextField();
        jLabel11 = new javax.swing.JLabel();
        inputCor = new JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        labelRenavam = new javax.swing.JLabel();
        inputRenavam = new JTextField();
        dateDataFabricacao = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        inputPrecoVenda = new JTextField();
        inputPrecoCompra = new JTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("jCheckBoxMenuItem3");

        jMenu1.setText("jMenu1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Veiculos");

        Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/cancel.png"))); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        btnCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/ok.png"))); // NOI18N
        btnCadastro.setText("Salvar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jLabel2.setText("Dados:");

        labelNome.setText("Nome:");

        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Ano Modelo:");

        inputAnoModelo.setModel(new javax.swing.DefaultComboBoxModel<>(selectAnos));
        inputAnoModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAnoModeloActionPerformed(evt);
            }
        });

        jLabel4.setText("Ano Fabricação:");

        inputAnoFabricacao.setModel(new javax.swing.DefaultComboBoxModel<>(selectAnos));

        jLabel5.setText("Combustivel:");

        inputCombustivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasolina", "Alcool", "Diesel", "GNV" }));

        jLabel6.setText("Placa(Letras e Números):");

        inputPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPlacaActionPerformed(evt);
            }
        });

        jLabel7.setText("Marca:");

        jLabel8.setText("Modelo:");

        jLabel9.setText("Principais Caracteristicas:");

        checkArCondicionado.setText("Ar Condicionado");
        checkArCondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkArCondicionadoActionPerformed(evt);
            }
        });

        checkAirBag.setText("Air Bag");
        checkAirBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAirBagActionPerformed(evt);
            }
        });

        checkCdPlayer.setText("CD Player");

        checkDirecaoHidraulica.setText("Direção Hidraulica");

        checkVidroEletrico.setText("Vidro Elétrico");

        checkTravaEletrica.setText("Trava Elétrica");
        checkTravaEletrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTravaEletricaActionPerformed(evt);
            }
        });

        checkCambioAutomatico.setText("Câmbio Automático");
        checkCambioAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkCambioAutomaticoActionPerformed(evt);
            }
        });

        checkAlarme.setText("Alarme");

        checkZeroKm.setText("0Km");

        checkDesembacadorTraseiro.setText("Desembaçador Traseiro");

        checkRodasLiga.setText("Rodas de Liga");
        checkRodasLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRodasLigaActionPerformed(evt);
            }
        });

        jLabel10.setText("KM:");

        jLabel11.setText("Cor:");

        jLabel12.setText("Data de Fabricação:");

        jLabel13.setText("Preço de Compra:");

        jLabel14.setText("Preço de Venda:");

        labelRenavam.setText("Renavam:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/delete-32.png"))); // NOI18N
        jButton1.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputAnoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(inputCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputPlaca)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(inputMarca)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkArCondicionado)
                                    .addComponent(checkCambioAutomatico))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkAirBag)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkCdPlayer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkAlarme)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkZeroKm)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkDirecaoHidraulica)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkVidroEletrico)
                                        .addGap(28, 28, 28)
                                        .addComponent(checkTravaEletrica))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkDesembacadorTraseiro)
                                        .addGap(26, 26, 26)
                                        .addComponent(checkRodasLiga))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(inputKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(inputCor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateDataFabricacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputPrecoCompra))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(inputPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNome)
                        .addGap(18, 18, 18)
                        .addComponent(labelRenavam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRenavam)
                    .addComponent(inputRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputAnoModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputAnoFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkArCondicionado)
                    .addComponent(checkAirBag)
                    .addComponent(checkCdPlayer)
                    .addComponent(checkDirecaoHidraulica)
                    .addComponent(checkVidroEletrico)
                    .addComponent(checkTravaEletrica))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkAlarme)
                        .addComponent(checkZeroKm)
                        .addComponent(checkDesembacadorTraseiro)
                        .addComponent(checkRodasLiga))
                    .addComponent(checkCambioAutomatico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cancelar)
                            .addComponent(jButton1)
                            .addComponent(btnCadastro)))
                    .addComponent(dateDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNomeActionPerformed

    private void checkArCondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkArCondicionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkArCondicionadoActionPerformed

    private void checkAirBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAirBagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAirBagActionPerformed

    private void checkTravaEletricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTravaEletricaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkTravaEletricaActionPerformed

    private void checkCambioAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkCambioAutomaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkCambioAutomaticoActionPerformed

    private void checkRodasLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRodasLigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkRodasLigaActionPerformed

    private void inputPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPlacaActionPerformed
    
    private Car getFormCar() {
    	Car c = new Car();
        c.setNome(inputNome.getText());
        c.setRenavam(inputRenavam.getText());
        c.setAnoModelo(Integer.parseInt(inputAnoModelo.getSelectedItem().toString()));
        c.setAnoFabricacao(Integer.parseInt(inputAnoFabricacao.getSelectedItem().toString()));
        c.setCombustivel(inputCombustivel.getSelectedItem().toString());
        c.setPlaca(inputPlaca.getText());
        c.setMarca(inputMarca.getText());
        c.setModelo(inputModelo.getText());
        c.setArCondicionado(checkArCondicionado.isSelected());
        c.setAirBag(checkAirBag.isSelected());
        c.setCdPlayer(checkCdPlayer.isSelected());
        c.setDirecaoHidraulica(checkDirecaoHidraulica.isSelected());
        c.setVidroEletrico(checkVidroEletrico.isSelected());
        c.setTravaEletrica(checkTravaEletrica.isSelected());
        c.setCambioAutomatico(checkCambioAutomatico.isSelected());
        c.setZeroKm(checkZeroKm.isSelected());
        c.setDesembacadorTraseiro(checkDesembacadorTraseiro.isSelected());
        c.setRodasLiga(checkRodasLiga.isSelected());
        c.setKm(Integer.parseInt(inputKilometragem.getText()));
        c.setCor(inputCor.getText());
        c.setPrecoCompra(Float.parseFloat(inputPrecoCompra.getText()));
        c.setPrecoVenda(Float.parseFloat(inputPrecoVenda.getText()));
        c.setDataFabricacao(dateDataFabricacao.getDate());
        
        return c;
    }
    
    private void preencheEditFormCar() {
        this.inputNome.setText(this.editCar.getNome());
        this.inputRenavam.setText(this.editCar.getRenavam());
        this.checkAirBag.setSelected(this.editCar.airBagInt() == 1);
        this.checkArCondicionado.setSelected(this.editCar.arCondicionadoInt() == 1);
        this.checkCdPlayer.setSelected(this.editCar.cdPlayerInt() == 1);
        this.checkDirecaoHidraulica.setSelected(this.editCar.direcaoHidraulicaInt() == 1);
        this.checkVidroEletrico.setSelected(this.editCar.vidroEletricoInt() == 1);
        this.checkTravaEletrica.setSelected(this.editCar.travaEletricaInt() == 1);
        this.checkCambioAutomatico.setSelected(this.editCar.cambioAutomaticoInt() == 1);
        this.checkAlarme.setSelected(this.editCar.AlarmeInt() == 1);
        this.checkZeroKm.setSelected(this.editCar.zeroKmInt() == 1);
        this.checkDesembacadorTraseiro.setSelected(this.editCar.desembacadorTraseiroInt() == 1);
        this.checkRodasLiga.setSelected(this.editCar.rodasLigaInt() == 1);
    }
    
    private boolean validateCar(Car c) {    	
    	if(c.getNome().trim().length() == 0) {
    		//mensagem de erro
    		return false;
    	}
    }

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
    	Car c = this.getFormCar();
    	
    	if(this.validateCar(c) == false){
    		return;
    	}
        
        if(this.editCar != null) {
            if (CarDAO.editCar(this.editCar.getId(), c)) {
                JOptionPane.showMessageDialog(jPanel1, "Cadastro Efetuado com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(jPanel1, "Ocorreu um Erro no Cadastro!");
            }
        } else {
            if (CarDAO.insertCar(c)) {
            JOptionPane.showMessageDialog(jPanel1, "Cadastro Efetuado com Sucesso!");

            } else {
                JOptionPane.showMessageDialog(jPanel1, "Ocorreu um Erro no Cadastro!");
            }
        }

    }//GEN-LAST:event_btnCadastroActionPerformed

    private void inputAnoModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAnoModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAnoModeloActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox checkAirBag;
    private javax.swing.JCheckBox checkAlarme;
    private javax.swing.JCheckBox checkArCondicionado;
    private javax.swing.JCheckBox checkCambioAutomatico;
    private javax.swing.JCheckBox checkCdPlayer;
    private javax.swing.JCheckBox checkDesembacadorTraseiro;
    private javax.swing.JCheckBox checkDirecaoHidraulica;
    private javax.swing.JCheckBox checkRodasLiga;
    private javax.swing.JCheckBox checkTravaEletrica;
    private javax.swing.JCheckBox checkVidroEletrico;
    private javax.swing.JCheckBox checkZeroKm;
    private com.toedter.calendar.JDateChooser dateDataFabricacao;
    private javax.swing.JComboBox<String> inputAnoFabricacao;
    private javax.swing.JComboBox<String> inputAnoModelo;
    private javax.swing.JComboBox<String> inputCombustivel;
    private JTextField inputCor;
    private JTextField inputKilometragem;
    private JTextField inputMarca;
    private JTextField inputModelo;
    private JTextField inputNome;
    private JTextField inputPlaca;
    private JTextField inputPrecoCompra;
    private JTextField inputPrecoVenda;
    private JTextField inputRenavam;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRenavam;
    // End of variables declaration//GEN-END:variables
}
